name: Python Lint

on:
  push:
    branches:
      - '**'  # Triggers on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change this version if needed

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 on script.py
        run: flake8 script.py
