name: PostgreSQL Service Test

on:
  push:
    branches:
      - '**'  # Run on push to any branch

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "PostgreSQL is up and running!"
              break
            else
              echo "PostgreSQL not yet ready... retrying ($i)"
              sleep 1
            fi
          done

      - name: Output Success Message
        run: echo "✅ PostgreSQL service is ready and accepting connections."
