name: PostgreSQL Service Test

on:
  push:
    branches:
      - '**'  # Run on push to any branch

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to start on localhost:5432..."
          while ! nc -z localhost 5432; do
            echo "PostgreSQL not ready yet. Retrying in 1s..."
            sleep 1
          done
          echo "PostgreSQL is up and running!"

      - name: Output Success Message
        run: echo "✅ PostgreSQL service is ready and accepting connections."
