name: GitHub repository secrets

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "The secret is \${{ secrets.SECRET }}"
